# Generated by Django 3.1.1 on 2020-09-10 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(blank=True, default='', max_length=20)),
                ('Last_Name', models.CharField(blank=True, default='', max_length=20)),
                ('Starting_Balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100000000)),
            ],
        ),
    ]
